"""B15-ZERO tests — exact Tr(phi^3) ground truth, hidden zeros, splits, delta-shift (R37).

T1  Catalan counts: 5 / 14 / 132 triangulations at n = 5 / 6 / 8 (also 2, 42 at n = 4, 7)
T2  Route A (triangulation sum) == Route B (factorization recursion) exactly on >= 200
    seeded rational points per n in {5, 6, 8}   [falsifier F2]
T3  every registered zero locus (arXiv:2312.16282 eq. 6.14 + cyclic images, n(n-3)/2 loci)
    annihilates A_n exactly, by BOTH routes    [falsifier F3]
T4  negative control: the same number of random rational linear constraints -> nonzero at
    >= 95% of points (registered threshold)
T5  2-split (arXiv:2405.09608 eq. 1.7): A_n == A_P(x) A_Q(y) exactly on >= 50 registered
    split points per split; transcription guards against eqs. (2.1)/(2.7); near-zero
    factorization (2312.16282 eq. 3.3) at n = 5
T6  delta-shift == NLSM Feynman rules (4-, 6-, 8-point) exactly; lower orders in 1/delta
    cancel exactly (2401.05483 eq. 2); 6-point cross-check against 2312.16282 eq. 7.20
T7  dataset: data/b15/zero_dataset_v1.json regenerated byte-for-byte (seed, generator sha256,
    canonical JSON), every stored value re-derived by Route A, and hash-stable
"""

import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fractions import Fraction as F

from b15_surf import certificate as C
from b15_surf.exact import fmt
from b15_surf.pir_bridge import domain_fact
from b15_surf.zero import dataset as D
from b15_surf.zero.delta_shift import nlsm6_eq_7_20, nlsm_from_shift
from b15_surf.zero.kinematics import X, c, chords, random_point
from b15_surf.zero.nlsm_feynman import nlsm_amplitude
from b15_surf.zero.recursion import amplitude_B
from b15_surf.zero.splits import (random_split_kinematics, registered_splits,
                                  split_locus_pairs, split_point)
from b15_surf.zero.triangulations import amplitude_A, catalan, triangulations
from b15_surf.zero.zeros import (random_constraints, registered_loci,
                                 sample_on_constraints, sample_on_locus)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED = D.SEED
N_AB_POINTS = 200
N_SPLIT_POINTS = 50
N_CONTROL_POINTS = 60
NONZERO_THRESHOLD = F(95, 100)


def t1_catalan():
    counts = {}
    for n, expect in ((4, 2), (5, 5), (6, 14), (7, 42), (8, 132)):
        got = len(triangulations(n))
        assert got == expect == catalan(n - 2), (n, got)
        counts[n] = got
    print(f"T1 Catalan counts: {counts}")
    return {"status": "PASS", "counts": {str(k): v for k, v in counts.items()}}


def t2_route_a_eq_b():
    rng = random.Random(SEED + 2)
    out = {}
    for n in (5, 6, 8):
        for _ in range(N_AB_POINTS):
            pt = random_point(n, rng)
            a, b = amplitude_A(pt, n), amplitude_B(pt, n)
            assert a == b, ("F2: Route A != Route B", n, pt)
        out[str(n)] = N_AB_POINTS
    print(f"T2 Route A == Route B on {N_AB_POINTS} points at each n in (5,6,8)")
    return {"status": "PASS", "points_per_n": out, "falsifier": "F2 not triggered"}


def t3_zeros():
    rng = random.Random(SEED + 3)
    out = {}
    for n in (5, 6, 8):
        L = registered_loci(n)
        assert len(L) == n * (n - 3) // 2, (n, len(L))
        for lid, pairs in L.items():
            for _ in range(3):
                pt = sample_on_locus(n, pairs, rng)
                assert all(c(pt, n, a, b) == 0 for (a, b) in pairs)
                assert amplitude_A(pt, n) == 0 and amplitude_B(pt, n) == 0, ("F3", lid)
        out[str(n)] = {"loci": len(L), "example_locus": {k: [f"c{a},{b}" for a, b in v]
                                                          for k, v in list(L.items())[:2]}}
    print(f"T3 hidden zeros: all n(n-3)/2 registered loci annihilate A_n exactly "
          f"({ {k: v['loci'] for k, v in out.items()} })")
    return {"status": "PASS", "per_n": out, "falsifier": "F3 not triggered"}


def t4_negative_control():
    rng = random.Random(SEED + 4)
    out = {}
    for n in (5, 6, 8):
        m = max(len(p) for p in registered_loci(n).values())
        nonzero = 0
        for _ in range(N_CONTROL_POINTS):
            A = random_constraints(n, m, rng)
            pt = sample_on_constraints(n, A, rng)
            if amplitude_B(pt, n) != 0:
                nonzero += 1
        rate = F(nonzero, N_CONTROL_POINTS)
        assert rate >= NONZERO_THRESHOLD, (n, rate)
        out[str(n)] = {"constraints": m, "nonzero_rate": fmt(rate)}
    print(f"T4 negative control: nonzero rates {out} (threshold {fmt(NONZERO_THRESHOLD)})")
    return {"status": "PASS", "per_n": out, "threshold": fmt(NONZERO_THRESHOLD)}


def t5_splits():
    rng = random.Random(SEED + 5)
    # transcription guards: eq. (2.7) [n=5, tau=(3,5,1)] and eq. (2.1) [n=6, tau=(5,1,3)]
    x = {(1, 4): F(2), (3, 5): F(3)}
    y = {(1, 3): F(5), (2, 5): F(7)}
    pt = split_point(5, 3, 5, 1, x, y)
    assert (pt[(1, 3)], pt[(1, 4)], pt[(2, 4)], pt[(2, 5)], pt[(3, 5)]) == (5, 7, 2, 7, 3), pt
    x = {(1, 3): F(1), (1, 5): F(2), (2, 5): F(3), (2, 6): F(4), (3, 6): F(5)}
    y = {(1, 4): F(7), (3, 5): F(11)}
    pt = split_point(6, 5, 1, 3, x, y)
    assert pt[(1, 4)] == 8 and pt[(2, 4)] == 7 and pt[(3, 6)] == 16 and pt[(4, 6)] == 5, pt
    assert split_locus_pairs(6, 5, 1, 3) == [(1, 3), (3, 5)]          # eq. (2.5)
    # eq. (1.7) on registered splits
    out = {}
    for n in (5, 6, 8):
        for sid, (i, j, k) in registered_splits(n).items():
            lp = split_locus_pairs(n, i, j, k)
            for _ in range(N_SPLIT_POINTS):
                Xp, xp, yp, nP, nQ = random_split_kinematics(n, i, j, k, rng)
                assert amplitude_A(Xp, n) == amplitude_B(xp, nP) * amplitude_B(yp, nQ), sid
                assert all(c(Xp, n, a, b) == 0 for (a, b) in lp)
            out[sid] = {"triangle": [i, j, k], "factors": [nP, nQ],
                        "vanishing_c": [f"c{a},{b}" for a, b in lp], "points": N_SPLIT_POINTS}
    # near-zero factorization, 2312.16282 eq. (3.3): n=5, c_{1,4}=0
    for _ in range(N_SPLIT_POINTS):
        pt = sample_on_locus(5, [(1, 4)], rng)
        lhs = amplitude_B(pt, 5)
        rhs = (1 / X(pt, 5, 1, 3) + 1 / X(pt, 5, 2, 5)) * (1 / X(pt, 5, 1, 4) + 1 / X(pt, 5, 3, 5))
        assert lhs == rhs
    print(f"T5 2-splits: eq. (1.7) exact on {N_SPLIT_POINTS} points x {len(out)} registered splits; "
          f"eq. (3.3) near-zero factorization exact at n=5")
    return {"status": "PASS", "splits": out, "near_zero_eq_3_3": {"points": N_SPLIT_POINTS}}


def t6_delta_shift():
    rng = random.Random(SEED + 6)
    out = {}
    for n, npts in ((4, 50), (6, 50), (8, 20)):
        for _ in range(npts):
            pt = random_point(n, rng)
            lim, low = nlsm_from_shift(pt, n)
            assert all(v == 0 for v in low), "lower orders in 1/delta did not cancel"
            fey = nlsm_amplitude(pt, n)
            assert lim == fey, (n, lim, fey)
            if n == 4:
                assert lim == -(pt[(1, 3)] + pt[(2, 4)])          # 2401.05483 §I
            if n == 6:
                assert lim == nlsm6_eq_7_20(pt)                   # 2312.16282 eq. 7.20
        out[str(n)] = npts
    print(f"T6 delta-shift == NLSM Feynman rules exactly at n=4,6,8 ({out}); "
          f"O(delta^-m) cancellations exact; eq. 7.20 cross-check exact")
    return {"status": "PASS", "points_per_n": out,
            "prescription": "lim delta^(n-2) A^delta_n, X_ee+delta, X_oo-delta (2401.05483 eq. 2)"}


def t7_dataset():
    ds = D.load()
    regen = D.build(SEED)
    assert regen["dataset_sha256"] == ds["dataset_sha256"], "dataset not hash-stable"
    assert regen["generator_sha256"] == ds["generator_sha256"], "generator changed; regenerate dataset"
    # every stored value re-derived by the independent Route A (TrPhi3 rows) / Feynman (NLSM rows)
    checked = 0
    for r in ds["records"]:
        n = r["n"]
        pt = {tuple(int(x) for x in k.split(",")): F(v) for k, v in r["point"].items()}
        if r["theory"] == "TrPhi3":
            val = amplitude_A(pt, n)
        elif r["theory"] == "NLSM":
            val = nlsm_amplitude(pt, n)
        else:
            from b15_surf.zero.delta_shift import shifted_point
            val = amplitude_A(shifted_point(pt, n, F(ds["registered"]["delta_shifted"])), n)
        assert val == F(r["value"]), r
        if r["on_zero_locus"]:
            assert val == 0
        checked += 1
    print(f"T7 dataset: {checked} records re-derived exactly; sha256 {ds['dataset_sha256'][:16]}… stable")
    return {"status": "PASS", "records": checked, "dataset_sha256": ds["dataset_sha256"],
            "generator_sha256": ds["generator_sha256"], "seed": ds["seed"]}


if __name__ == "__main__":
    if not os.path.exists(D.DATASET_PATH):
        D.write()
    r1 = t1_catalan()
    r2 = t2_route_a_eq_b()
    r3 = t3_zeros()
    r4 = t4_negative_control()
    r5 = t5_splits()
    r6 = t6_delta_shift()
    r7 = t7_dataset()
    results = {"T1_catalan": r1, "T2_routeA_eq_routeB": r2, "T3_zeros": r3,
               "T4_negative_control": r4, "T5_splits": r5, "T6_delta_shift_nlsm": r6,
               "T7_dataset": r7}
    witness = {"routes": ["planar-feynman-sum (Route A)", "factorization-recursion (Route B)"],
               "loci_per_n": {k: v["loci"] for k, v in r3["per_n"].items()},
               "split_factorizations": {k: v["vanishing_c"] for k, v in r5["splits"].items()}}
    fact = domain_fact(
        benchmark="B15-ZERO",
        content={"subject": "Tr(phi^3) tree amplitudes n<=8: hidden zeros, 2-splits, delta-shift->NLSM",
                 "dataset_sha256": r7["dataset_sha256"]},
        verdict="PERMITTED", evidence_level="E0", soundness="SOUND",
        witness=witness, impossibility_certificate=None, assumptions=[], warnings=[],
        measurement_interface="none (theory-internal identities; exact rational evaluation)")
    cert = C.build(
        benchmark="B15-ZERO",
        problem="B15-ZERO: exact ground-truth Tr(phi^3) amplitude dataset — two routes, hidden zeros, "
                "2-splits, delta-shift to NLSM vs independent Feynman rules (R37)",
        headline="Route A == Route B on 200 pts/n; all n(n-3)/2 zero loci vanish exactly; splits "
                 "factorize exactly (eq. 1.7); lim delta^(n-2) A^delta == NLSM Feynman at 4/6/8 pts; "
                 "dataset hash-stable",
        certificate_class="EXACT-RATIONAL (same class as B1/B2/B7); perturbative-amplitude identities",
        results=results, soundness="SOUND", warnings=[],
        ground_truth_route="planar-feynman-sum",
        evidence_level="E0", pir_level="L2", assumptions=[],
        falsifier_direction="F2: Route A != Route B anywhere -> generator REJECTED, no dataset; "
                            "F3: a registered zero not vanishing exactly -> erratum/open item, never a patch",
        seed=SEED, generator_sha256=r7["generator_sha256"],
        m_layer_stipulations=[
            "Theory-internal perturbative identities (tree level, planar); no measurement interface",
            "Kinematic conventions transcribed from arXiv:2312.16282 eqs. 2.2-2.4",
            "NLSM Feynman route fixed to mostly-plus signature so that A_4 = -(X13+X24) (2401.05483 §I); "
            "the 6- and 8-point equalities carry no further freedom",
            "Hidden zeros are unobservable loci: E0 mathematical warrant, no measurement warrant",
        ],
        calibration_route="none required (exact identities; seeded rational points registered)",
        verdict="PERMITTED", witness=witness, impossibility_certificate=None,
        inputs={"dataset_path": "data/b15/zero_dataset_v1.json", "dataset_sha256": r7["dataset_sha256"],
                "seed": SEED, "points_per_n_T2": N_AB_POINTS, "split_points": N_SPLIT_POINTS,
                "nonzero_rate_threshold": fmt(NONZERO_THRESHOLD)},
        pir_facts=[fact.to_dict()],
    )
    C.save(cert, "b15_zero_certificate.json")
    print("\nCertificate written: certificates/b15_zero_certificate.json")
    print("ALL B15-ZERO TESTS PASS")
